import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Navbar from "@/components/dashboard/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <body>
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Navbar />
        <main>
         {children}
        </main>
      </SidebarInset>
    </SidebarProvider>
  </body>
  );
}
