import type { Metadata } from "next";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Navbar from "@/components/dashboard/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <body>
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Navbar />
        <main>
         {children}
        </main>
      </SidebarInset>
    </SidebarProvider>
  </body>
  );
}
