version: '3.8'

services:
  ollama-api-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_INSTANCES=http://host.docker.internal:11434
      - LOAD_BALANCING_STRATEGY=least_connections
      - PORT=8000
    restart: unless-stopped
    networks:
      - ollama-network


networks:
  ollama-network:
    driver: bridge
